export const projectData = [
  {
    id: Math.floor(Math.random() * 10),
    title: "Todo Application",
    description:
      "Learn to build a To-do application by watching this tutorial project.",
    tag: "Html",
    price: "free",
    stack: ["Html", "Css", "JavaScript"],
    coverImg: "",
    tutor: "Erasmus Mensah",
    level: "beginner",
    sort: "beginner",
  },
  {
    id: Math.floor(Math.random() * 10),
    title: "Facebook Clone",
    description:
      "Learn to clone the famous social chatting application Facebook by watching this tutorial project.",
    tag: "React",
    price: "free",
    stack: ["React", "React Router", "Firebase", "React Icons"],
    coverImg: "",
    tutor: "Erasmus Mensah",
    level: "advanced",
    sort: ["free", "intermediate", "advanced"],
  },
  {
    id: Math.floor(Math.random() * 10),
    title: "Google Clone",
    description:
      "Learn to clone the searching application Google by watching this tutorial project.",
    tag: "Html",
    price: "free",
    stack: ["Html", "Css", "JavaScript", "API"],
    coverImg: "",
    tutor: "Erasmus Mensah",
    level: "beginner",
    sort: ["free", "beginner"],
  },
  {
    id: Math.floor(Math.random() * 10),
    title: "Twitter Clone",
    description:
      "Learn to clone the famous social application Twitter by watching this tutorial project.",
    tag: "React",
    price: "free",
    stack: ["React", "Twitter API", "Firebase", "React Icons"],
    coverImg: "",
    tutor: "Erasmus Mensah",
    level: "intermediate",
    sort: ["free", "intermediate"],
  },
  {
    id: Math.floor(Math.random() * 10),
    title: "Netflix Clone",
    description:
      "Learn to clone the famous movies application Netflix by watching this tutorial project.",
    tag: "React",
    price: "free",
    stack: ["React", "TMDB API", "Firebase"],
    coverImg: "",
    tutor: "Erasmus Mensah",
    level: "intermediate",
    sort: ["free", "intermediate"],
  },
  {
    id: Math.floor(Math.random() * 10),
    title: "Instagram Clone",
    description:
      "Learn to clone the famous social application Instagram by watching this tutorial project.",
    tag: "React",
    price: "free",
    stack: ["React", "Firebase", "React Icons"],
    coverImg: "",
    tutor: "Erasmus Mensah",
    level: "intermediate",
    sort: ["free", "intermediate"],
  },
  {
    id: Math.floor(Math.random() * 10),
    title: "Dictionary Application",
    description:
      "Learn to a dictionary application by watching this tutorial project.",
    tag: "Html",
    price: "free",
    stack: ["Html", "Css", "JavaScript", "API"],
    coverImg: "",
    tutor: "Erasmus Mensah",
    level: "beginner",
    sort: ["free", "beginner"],
  },
  {
    id: Math.floor(Math.random() * 10),
    title: "Currency Convertor Application",
    description:
      "Learn to a currency convertor application intergrating currency API by watching this tutorial project.",
    tag: "Html",
    price: "free",
    stack: ["Html", "Css", "JavaScript", "API"],
    coverImg: "",
    tutor: "Erasmus Mensah",
    level: "beginner",
    sort: ["free", "beginner"],
  },
  {
    id: Math.floor(Math.random() * 10),
    title: "YouTube Clone",
    description:
      "Learn to clone the famous video streaming application intergrating YouTube API by watching this tutorial project.",
    tag: "React",
    price: "free",
    stack: ["React", "YouTube API", "Firebase"],
    coverImg: "",
    tutor: "Erasmus Mensah",
    level: "advanced",
    sort: ["free", "advanced"],
  },
  {
    id: Math.floor(Math.random() * 10),
    title: "Spotify Clone",
    description:
      "Clone the famous music streaming application intergrating Spotify API by watching this tutorial project.",
    tag: "React",
    price: "free",
    stack: ["React", "Spotify API", "Firebase"],
    coverImg: "",
    tutor: "Erasmus Mensah",
    level: "advanced",
    sort: ["free", "advanced"],
  },
  {
    id: Math.floor(Math.random() * 10),
    title: "Slack Clone",
    description:
      "Clone the famous team collaboration application Slack by watching this tutorial project.",
    tag: "React",
    price: "free",
    stack: ["React", "Firebase"],
    coverImg: "",
    tutor: "Erasmus Mensah",
    level: "advanced",
    sort: ["free", "advanced"],
  },
];
